### ISSUE TITLE
Unable to establish connection error when using trax

### ISSUE THREAD

**Issue by davisking** [vicoslab/vot-toolkit#33] opened 2015-04-12 13:31 UTC
In my tracker_mytracker.m file I put:

    tracker_trax = true

and then in configuration.m I put:

    set_global_variable('trax_client', 'traxclient');

I've also compiled trax with cmake and ran make install. It seems to compile fine and I've got the library and client tool in /usr/local/bin and /usr/local/lib.  I also compiled the c++ ncc_trax example and set tracker_command to reference it.  However, it doesn't seem to work.  In particular, when I try to do run_test this is what happens (I'm using Octave to run the scripts):

```
octave:3> run_test
Initializing VOT environment ...
Compiling MEX files ...

***************************************************************************

Welcome to the VOT sandbox!
This process will help you prepare your tracker for the evaluation.
When beginning with the integration it is recommended to follow the steps 
a, b, c to verify the execution and the output data.

***************************************************************************

Choose action:
  a - Generate a directory with input data for manual test
  b - Run tracker once within the evaluation
  d - Enable debug output
  e - Exit
Choose action: a
Choose a sequence:
  1 - "ball"
  2 - "basketball"
  3 - "bicycle"
  4 - "bolt"
  5 - "car"
  6 - "david"
  7 - "diving"
  8 - "drunk"
  9 - "fernando"
  10 - "fish1"
  11 - "fish2"
  12 - "gymnastics"
  13 - "hand1"
  14 - "hand2"
  15 - "jogging"
  16 - "motocross"
  17 - "polarbear"
  18 - "skating"
  19 - "sphere"
  20 - "sunshade"
  21 - "surfing"
  22 - "torus"
  23 - "trellis"
  24 - "tunnel"
  25 - "woman"
Selected sequence: 4
Input data generated in directory "/tmp/oct-XWI5M5"
Open the directory in a terminal and manually execute the tracker command.
The current command as defined in the environment is: traxclient  -r 1 -e "MATLAB_ROOT=/usr" -I "/tmp/oct-XWI5M5/images.txt" -G "/home/davis/temp/new-vot-toolkit/working_dir/sequences/bolt/groundtruth.txt" -O "/tmp/oct-XWI5M5/output.txt" -S "/tmp/oct-XWI5M5/initialization.txt" -T "/tmp/oct-XWI5M5/timing.txt" -- /home/davis/temp/new-vot-toolkit/working_dir/../examples/cpp/ncc_trax
Once the tracker is working as expected, delete the directory.
```
Ok, so I run this in a terminal window and it hangs for maybe 30 seconds and then eventually prints the unable to establish connection error:
```
/tmp/oct-XWI5M5$ traxclient  -r 1 -e "MATLAB_ROOT=/usr" -I "/tmp/oct-XWI5M5/images.txt" -G "/home/davis/temp/new-vot-toolkit/working_dir/sequences/bolt/groundtruth.txt" -O "/tmp/oct-XWI5M5/output.txt" -S "/tmp/oct-XWI5M5/initialization.txt" -T "/tmp/oct-XWI5M5/timing.txt" -- /home/davis/temp/new-vot-toolkit/working_dir/../examples/cpp/ncc_trax

Error: Unable to establish connection
```

I get the same error if I try to run it through Octave as well:

```
Choose action:
  a - Generate a directory with input data for manual test
  b - Run tracker once within the evaluation
  d - Enable debug output
  e - Exit
Choose action: b
Choose a sequence:
  1 - "ball"
  2 - "basketball"
  3 - "bicycle"
  4 - "bolt"
  5 - "car"
  6 - "david"
  7 - "diving"
  8 - "drunk"
  9 - "fernando"
  10 - "fish1"
  11 - "fish2"
  12 - "gymnastics"
  13 - "hand1"
  14 - "hand2"
  15 - "jogging"
  16 - "motocross"
  17 - "polarbear"
  18 - "skating"
  19 - "sphere"
  20 - "sunshade"
  21 - "surfing"
  22 - "torus"
  23 - "trellis"
  24 - "tunnel"
  25 - "woman"
Selected sequence: 4
Sequence "bolt"
Error: Unable to establish connection
```

**Comment by lukacu** [comment] 2015-04-12 16:48
If the traxclient reports "Unable to establish connection" this means that there is a protocol error or a crash of the tracker executable because of an error. Nothing else will work, so we first have to make the test procedure pass. If you run the ncc_trax executable standalone, what does it output? It should write a TraX "hello" message and then wait. Does it do that?

**Comment by davisking** [comment] 2015-04-12 17:39
When I run ncc_trax on it's own it says:
```
@@TRAX:hello "trax.image=path" "trax.region=rectangle" "trax.version=1"
```
and then waits.

**Comment by lukacu** [comment] 2015-04-12 17:48
Ok, so the executable works. I will try to reproduce the error.

**Comment by lukacu** [comment] 2015-07-01 20:46
I have finally attempted to duplicate the problem with development branch, but run_test is working as expected. The toolkit has changed quite a bit, so perhaps the fix was implicit. In any case I am now closing the bug, please reopen it if you are still able to replicate it (with the 2015 version that is currently not merged to master branch).

**Closed by lukacu** 2015-07-01 20:46 UTC
Labels: trax
